// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendJoin struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendJoin) Reset()         { *m = SendJoin{} }
func (m *SendJoin) String() string { return proto.CompactTextString(m) }
func (*SendJoin) ProtoMessage()    {}
func (*SendJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *SendJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendJoin.Unmarshal(m, b)
}
func (m *SendJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendJoin.Marshal(b, m, deterministic)
}
func (m *SendJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendJoin.Merge(m, src)
}
func (m *SendJoin) XXX_Size() int {
	return xxx_messageInfo_SendJoin.Size(m)
}
func (m *SendJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_SendJoin.DiscardUnknown(m)
}

var xxx_messageInfo_SendJoin proto.InternalMessageInfo

func (m *SendJoin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetJoin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJoin) Reset()         { *m = GetJoin{} }
func (m *GetJoin) String() string { return proto.CompactTextString(m) }
func (*GetJoin) ProtoMessage()    {}
func (*GetJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *GetJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJoin.Unmarshal(m, b)
}
func (m *GetJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJoin.Marshal(b, m, deterministic)
}
func (m *GetJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJoin.Merge(m, src)
}
func (m *GetJoin) XXX_Size() int {
	return xxx_messageInfo_GetJoin.Size(m)
}
func (m *GetJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJoin.DiscardUnknown(m)
}

var xxx_messageInfo_GetJoin proto.InternalMessageInfo

type SendMessage struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Smsg                 string   `protobuf:"bytes,3,opt,name=smsg,proto3" json:"smsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessage) Reset()         { *m = SendMessage{} }
func (m *SendMessage) String() string { return proto.CompactTextString(m) }
func (*SendMessage) ProtoMessage()    {}
func (*SendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *SendMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessage.Unmarshal(m, b)
}
func (m *SendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessage.Marshal(b, m, deterministic)
}
func (m *SendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessage.Merge(m, src)
}
func (m *SendMessage) XXX_Size() int {
	return xxx_messageInfo_SendMessage.Size(m)
}
func (m *SendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessage proto.InternalMessageInfo

func (m *SendMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendMessage) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SendMessage) GetSmsg() string {
	if m != nil {
		return m.Smsg
	}
	return ""
}

type GetMessage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Rmsg                 string   `protobuf:"bytes,4,opt,name=rmsg,proto3" json:"rmsg,omitempty"`
	Time                 string   `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessage) Reset()         { *m = GetMessage{} }
func (m *GetMessage) String() string { return proto.CompactTextString(m) }
func (*GetMessage) ProtoMessage()    {}
func (*GetMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *GetMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessage.Unmarshal(m, b)
}
func (m *GetMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessage.Marshal(b, m, deterministic)
}
func (m *GetMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessage.Merge(m, src)
}
func (m *GetMessage) XXX_Size() int {
	return xxx_messageInfo_GetMessage.Size(m)
}
func (m *GetMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessage proto.InternalMessageInfo

func (m *GetMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetMessage) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *GetMessage) GetRmsg() string {
	if m != nil {
		return m.Rmsg
	}
	return ""
}

func (m *GetMessage) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type SendAllMessage struct {
	Usr                  string   `protobuf:"bytes,1,opt,name=usr,proto3" json:"usr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAllMessage) Reset()         { *m = SendAllMessage{} }
func (m *SendAllMessage) String() string { return proto.CompactTextString(m) }
func (*SendAllMessage) ProtoMessage()    {}
func (*SendAllMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *SendAllMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAllMessage.Unmarshal(m, b)
}
func (m *SendAllMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAllMessage.Marshal(b, m, deterministic)
}
func (m *SendAllMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAllMessage.Merge(m, src)
}
func (m *SendAllMessage) XXX_Size() int {
	return xxx_messageInfo_SendAllMessage.Size(m)
}
func (m *SendAllMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAllMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendAllMessage proto.InternalMessageInfo

func (m *SendAllMessage) GetUsr() string {
	if m != nil {
		return m.Usr
	}
	return ""
}

type GetAllMessage struct {
	Msgs                 []*GetMessage `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetAllMessage) Reset()         { *m = GetAllMessage{} }
func (m *GetAllMessage) String() string { return proto.CompactTextString(m) }
func (*GetAllMessage) ProtoMessage()    {}
func (*GetAllMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *GetAllMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllMessage.Unmarshal(m, b)
}
func (m *GetAllMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllMessage.Marshal(b, m, deterministic)
}
func (m *GetAllMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllMessage.Merge(m, src)
}
func (m *GetAllMessage) XXX_Size() int {
	return xxx_messageInfo_GetAllMessage.Size(m)
}
func (m *GetAllMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllMessage proto.InternalMessageInfo

func (m *GetAllMessage) GetMsgs() []*GetMessage {
	if m != nil {
		return m.Msgs
	}
	return nil
}

type SendUsers struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendUsers) Reset()         { *m = SendUsers{} }
func (m *SendUsers) String() string { return proto.CompactTextString(m) }
func (*SendUsers) ProtoMessage()    {}
func (*SendUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{6}
}

func (m *SendUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendUsers.Unmarshal(m, b)
}
func (m *SendUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendUsers.Marshal(b, m, deterministic)
}
func (m *SendUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendUsers.Merge(m, src)
}
func (m *SendUsers) XXX_Size() int {
	return xxx_messageInfo_SendUsers.Size(m)
}
func (m *SendUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_SendUsers.DiscardUnknown(m)
}

var xxx_messageInfo_SendUsers proto.InternalMessageInfo

type GetUsers struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsers) Reset()         { *m = GetUsers{} }
func (m *GetUsers) String() string { return proto.CompactTextString(m) }
func (*GetUsers) ProtoMessage()    {}
func (*GetUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{7}
}

func (m *GetUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsers.Unmarshal(m, b)
}
func (m *GetUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsers.Marshal(b, m, deterministic)
}
func (m *GetUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsers.Merge(m, src)
}
func (m *GetUsers) XXX_Size() int {
	return xxx_messageInfo_GetUsers.Size(m)
}
func (m *GetUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsers.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsers proto.InternalMessageInfo

func (m *GetUsers) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func init() {
	proto.RegisterType((*SendJoin)(nil), "chat.SendJoin")
	proto.RegisterType((*GetJoin)(nil), "chat.GetJoin")
	proto.RegisterType((*SendMessage)(nil), "chat.SendMessage")
	proto.RegisterType((*GetMessage)(nil), "chat.GetMessage")
	proto.RegisterType((*SendAllMessage)(nil), "chat.SendAllMessage")
	proto.RegisterType((*GetAllMessage)(nil), "chat.GetAllMessage")
	proto.RegisterType((*SendUsers)(nil), "chat.SendUsers")
	proto.RegisterType((*GetUsers)(nil), "chat.GetUsers")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xdf, 0x4a, 0xf4, 0x30,
	0x10, 0xc5, 0x69, 0x9a, 0x7e, 0xbb, 0x9d, 0x65, 0xfb, 0xad, 0x71, 0x2f, 0x4a, 0x2f, 0x64, 0x09,
	0x0a, 0x05, 0x61, 0x2f, 0x56, 0x7d, 0x00, 0x11, 0x29, 0x08, 0xde, 0x54, 0x7c, 0x80, 0x6a, 0x63,
	0x5b, 0xd8, 0x36, 0xd2, 0xc4, 0xa7, 0xf3, 0xe5, 0x64, 0x26, 0xdb, 0x3f, 0xb0, 0x77, 0x27, 0x33,
	0xbf, 0x39, 0x39, 0x19, 0x02, 0xf0, 0x59, 0x17, 0x76, 0xff, 0xdd, 0x6b, 0xab, 0x05, 0x47, 0x2d,
	0xaf, 0x60, 0xf9, 0xa6, 0xba, 0xf2, 0x45, 0x37, 0x9d, 0x10, 0xc0, 0xbb, 0xa2, 0x55, 0xb1, 0xb7,
	0xf3, 0xd2, 0x30, 0x27, 0x2d, 0x43, 0x58, 0x64, 0xca, 0x62, 0x5b, 0x3e, 0xc3, 0x0a, 0xd1, 0x57,
	0x65, 0x4c, 0x51, 0x29, 0xa4, 0xbf, 0x7a, 0xdd, 0x0e, 0x34, 0x6a, 0x11, 0x01, 0xb3, 0x3a, 0x66,
	0x54, 0x61, 0x56, 0x23, 0x63, 0x5a, 0x53, 0xc5, 0xbe, 0x63, 0x50, 0xcb, 0x1a, 0x20, 0x53, 0x76,
	0x70, 0x89, 0x80, 0x35, 0x25, 0x79, 0xf8, 0x39, 0x6b, 0xca, 0xd1, 0x95, 0x9d, 0xb9, 0xfa, 0x73,
	0xd7, 0x1e, 0x5d, 0xb9, 0x63, 0x50, 0x63, 0xcd, 0x36, 0xad, 0x8a, 0x03, 0x57, 0x43, 0x2d, 0x25,
	0x44, 0x18, 0xf8, 0xf1, 0x78, 0x1c, 0x6e, 0xdb, 0x80, 0xff, 0x63, 0xfa, 0x53, 0x64, 0x94, 0xf2,
	0x01, 0xd6, 0x99, 0xb2, 0x33, 0xe4, 0x1a, 0x78, 0x6b, 0x2a, 0x13, 0x7b, 0x3b, 0x3f, 0x5d, 0x1d,
	0x36, 0x7b, 0xda, 0xd8, 0x14, 0x38, 0xa7, 0xae, 0x5c, 0x41, 0x88, 0xd6, 0xef, 0x46, 0xf5, 0x46,
	0xee, 0x60, 0x99, 0x29, 0x4b, 0x5a, 0x6c, 0x21, 0xc0, 0xbd, 0xb9, 0xf9, 0x30, 0x77, 0x87, 0xc3,
	0xaf, 0x07, 0xc1, 0x53, 0x5d, 0x58, 0x23, 0x6e, 0x80, 0xd3, 0xae, 0x23, 0x67, 0x3c, 0xec, 0x3e,
	0x59, 0x8f, 0x17, 0x51, 0xfb, 0x16, 0x38, 0xb6, 0xc4, 0xc5, 0x84, 0x9d, 0x02, 0x24, 0x67, 0x91,
	0xc4, 0x3d, 0x2c, 0x06, 0xb9, 0x9d, 0xf8, 0xe9, 0x4d, 0xc9, 0xe5, 0x38, 0x32, 0x7b, 0x68, 0x0a,
	0x81, 0x8b, 0xfc, 0x7f, 0x9a, 0xa1, 0x42, 0x12, 0x8d, 0x38, 0x9d, 0x3f, 0xfe, 0xd1, 0x87, 0xb9,
	0xfb, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x4d, 0xcf, 0x69, 0x3e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatsClient is the client API for Chats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatsClient interface {
	Join(ctx context.Context, in *SendJoin, opts ...grpc.CallOption) (*GetJoin, error)
	Send(ctx context.Context, in *SendMessage, opts ...grpc.CallOption) (*GetMessage, error)
	Message(ctx context.Context, in *SendAllMessage, opts ...grpc.CallOption) (*GetAllMessage, error)
	Users(ctx context.Context, in *SendUsers, opts ...grpc.CallOption) (*GetUsers, error)
}

type chatsClient struct {
	cc *grpc.ClientConn
}

func NewChatsClient(cc *grpc.ClientConn) ChatsClient {
	return &chatsClient{cc}
}

func (c *chatsClient) Join(ctx context.Context, in *SendJoin, opts ...grpc.CallOption) (*GetJoin, error) {
	out := new(GetJoin)
	err := c.cc.Invoke(ctx, "/chat.Chats/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatsClient) Send(ctx context.Context, in *SendMessage, opts ...grpc.CallOption) (*GetMessage, error) {
	out := new(GetMessage)
	err := c.cc.Invoke(ctx, "/chat.Chats/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatsClient) Message(ctx context.Context, in *SendAllMessage, opts ...grpc.CallOption) (*GetAllMessage, error) {
	out := new(GetAllMessage)
	err := c.cc.Invoke(ctx, "/chat.Chats/Message", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatsClient) Users(ctx context.Context, in *SendUsers, opts ...grpc.CallOption) (*GetUsers, error) {
	out := new(GetUsers)
	err := c.cc.Invoke(ctx, "/chat.Chats/Users", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatsServer is the server API for Chats service.
type ChatsServer interface {
	Join(context.Context, *SendJoin) (*GetJoin, error)
	Send(context.Context, *SendMessage) (*GetMessage, error)
	Message(context.Context, *SendAllMessage) (*GetAllMessage, error)
	Users(context.Context, *SendUsers) (*GetUsers, error)
}

// UnimplementedChatsServer can be embedded to have forward compatible implementations.
type UnimplementedChatsServer struct {
}

func (*UnimplementedChatsServer) Join(ctx context.Context, req *SendJoin) (*GetJoin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedChatsServer) Send(ctx context.Context, req *SendMessage) (*GetMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedChatsServer) Message(ctx context.Context, req *SendAllMessage) (*GetAllMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Message not implemented")
}
func (*UnimplementedChatsServer) Users(ctx context.Context, req *SendUsers) (*GetUsers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Users not implemented")
}

func RegisterChatsServer(s *grpc.Server, srv ChatsServer) {
	s.RegisterService(&_Chats_serviceDesc, srv)
}

func _Chats_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendJoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chats/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServer).Join(ctx, req.(*SendJoin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chats_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chats/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServer).Send(ctx, req.(*SendMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chats_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAllMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chats/Message",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServer).Message(ctx, req.(*SendAllMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chats_Users_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUsers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatsServer).Users(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chats/Users",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatsServer).Users(ctx, req.(*SendUsers))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chats",
	HandlerType: (*ChatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Chats_Join_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Chats_Send_Handler,
		},
		{
			MethodName: "Message",
			Handler:    _Chats_Message_Handler,
		},
		{
			MethodName: "Users",
			Handler:    _Chats_Users_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
